# Site settings
title: Rick Tryfle
email: info@rick-tryfle.com
description: > # this means to ignore newlines until "baseurl:"
  Sound Fetishist, Turntablist, Producer
  Herne, Germany
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rick-tryfle.com" # the base hostname & protocol for your site
twitter_username: rick_tryfle
soundcloud_username: rick-tryfle

# Build settings
markdown: kramdown
